version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - transport.host=127.0.0.1
      - discovery.type:single-node
      - http.port=9200
      - http.cors.allow-origin=*
      - http.cors.enabled=true
  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
      - "1358:1358"
    links:
      - elasticsearch
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
  luqs_dev_data:
